"use client"
import { MantineProvider } from "@mantine/core"
import { Notifications } from "@mantine/notifications"

export const metadata = {
  title: 'Login page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><MantineProvider withNormalizeCSS withGlobalStyles> <Notifications />{children}</MantineProvider></body>
    </html>
  )
}